In [1]:
import numpy as np
import pandas as pd

In [2]:
movies_df = pd.read_csv('../data/movies_clean.csv')
reviews_df = pd.read_csv('../data/train_data.csv')

del movies_df['Unnamed: 0']
del reviews_df['Unnamed: 0']

In [3]:
movies_df.head()

movie_id                                              movie  \
0         8      Edison Kinetoscopic Record of a Sneeze (1894)   
1        10                La sortie des usines Lumière (1895)   
2        12                      The Arrival of a Train (1896)   
3        25  The Oxford and Cambridge University Boat Race ...   
4        91                         Le manoir du diable (1896)   

               genre  date  1800's  1900's  2000's  History  News  Horror  \
0  Documentary|Short  1894       1       0       0        0     0       0   
1  Documentary|Short  1895       1       0       0        0     0       0   
2  Documentary|Short  1896       1       0       0        0     0       0   
3                NaN  1895       1       0       0        0     0       0   
4       Short|Horror  1896       1       0       0        0     0       1   

   ...  Fantasy  Romance  Game-Show  Action  Documentary  Animation  Comedy  \
0  ...        0        0          0       0            1          0       0   
1  ...        0        0          0       0            1          0       0   
2  ...        0        0          0       0            1          0       0   
3  ...        0        0          0       0            0          0       0   
4  ...        0        0          0       0            0          0       0   

   Short  Western  Thriller  
0      1        0         0  
1      1        0         0  
2      1        0         0  
3      0        0         0  
4      1        0         0  

[5 rows x 35 columns]

In [4]:
reviews_df.head()

user_id  movie_id  rating   timestamp                 date  month_1  \
0    37287   2171847       6  1362062307  2013-02-28 14:38:27        0   
1    33140    444778       8  1362062624  2013-02-28 14:43:44        0   
2     6338   1411238       6  1362062838  2013-02-28 14:47:18        0   
3    43691   1496422       7  1362063503  2013-02-28 14:58:23        0   
4    33799    118799       5  1362063653  2013-02-28 15:00:53        0   

   month_2  month_3  month_4  month_5  ...  month_9  month_10  month_11  \
0        0        0        0        0  ...        0         0         0   
1        0        0        0        0  ...        0         0         0   
2        0        0        0        0  ...        0         0         0   
3        0        0        0        0  ...        0         0         0   
4        0        0        0        0  ...        0         0         0   

   month_12  year_2013  year_2014  year_2015  year_2016  year_2017  year_2018  
0         0          1          0          0          0          0          0  
1         0          1          0          0          0          0          0  
2         0          1          0          0          0          0          0  
3         0          1          0          0          0          0          0  
4         0          1          0          0          0          0          0  

[5 rows x 23 columns]

### creating ranked df

In [5]:
rating_mean = reviews_df.groupby('movie_id')['rating'].mean()
rating_count = reviews_df.groupby('movie_id')['rating'].count()
rating_latest = reviews_df.groupby('movie_id')['timestamp'].max()

In [6]:
rating_latest[20629]

1362633757

In [7]:
movies_df

movie_id                                              movie  \
0             8      Edison Kinetoscopic Record of a Sneeze (1894)   
1            10                La sortie des usines Lumière (1895)   
2            12                      The Arrival of a Train (1896)   
3            25  The Oxford and Cambridge University Boat Race ...   
4            91                         Le manoir du diable (1896)   
...         ...                                                ...   
31240   8335880                                      Loro 2 (2018)   
31241   8342748         Hari Kondabolu: Warn Your Relatives (2018)   
31242   8342946                Tig Notaro: Happy To Be Here (2018)   
31243   8402090                              Cumali Ceber 2 (2018)   
31244   8439854                                Lust Stories (2018)   

                   genre  date  1800's  1900's  2000's  History  News  Horror  \
0      Documentary|Short  1894       1       0       0        0     0       0   
1      Documentary|Short  1895       1       0       0        0     0       0   
2      Documentary|Short  1896       1       0       0        0     0       0   
3                    NaN  1895       1       0       0        0     0       0   
4           Short|Horror  1896       1       0       0        0     0       1   
...                  ...   ...     ...     ...     ...      ...   ...     ...   
31240          Biography  2018       0       0       1        0     0       0   
31241             Comedy  2018       0       0       1        0     0       0   
31242             Comedy  2018       0       0       1        0     0       0   
31243             Comedy  2018       0       0       1        0     0       0   
31244              Drama  2018       0       0       1        0     0       0   

       ...  Fantasy  Romance  Game-Show  Action  Documentary  Animation  \
0      ...        0        0          0       0            1          0   
1      ...        0        0          0       0            1          0   
2      ...        0        0          0       0            1          0   
3      ...        0        0          0       0            0          0   
4      ...        0        0          0       0            0          0   
...    ...      ...      ...        ...     ...          ...        ...   
31240  ...        0        0          0       0            0          0   
31241  ...        0        0          0       0            0          0   
31242  ...        0        0          0       0            0          0   
31243  ...        0        0          0       0            0          0   
31244  ...        0        0          0       0            0          0   

       Comedy  Short  Western  Thriller  
0           0      1        0         0  
1           0      1        0         0  
2           0      1        0         0  
3           0      0        0         0  
4           0      1        0         0  
...       ...    ...      ...       ...  
31240       0      0        0         0  
31241       1      0        0         0  
31242       1      0        0         0  
31243       1      0        0         0  
31244       0      0        0         0  

[31245 rows x 35 columns]

In [8]:
def create_ranked_df(movies_df: pd.DataFrame = movies_df, reviews_df: pd.DataFrame = reviews_df):
    rating_mean = reviews_df.groupby('movie_id')['rating'].mean()
    rating_count = reviews_df.groupby('movie_id')['rating'].count()
    rating_latest = reviews_df.groupby('movie_id')['timestamp'].max()
    rating_df = pd.DataFrame({"mean": rating_mean, "count": rating_count, "latest_ts": rating_latest})

    ranked_movie = movies_df.merge(rating_df, how='left', on='movie_id', right_index=True)
    ranked_movie.sort_values(["mean","count","latest_ts"], ascending=False, inplace=True)
    ranked_movie = ranked_movie[ranked_movie['count'] > 4][["movie", "mean","count","latest_ts"]]

    return ranked_movie
    


In [9]:
ranked_df = create_ranked_df()
ranked_df

Empty DataFrame
Columns: [movie, mean, count, latest_ts]
Index: []

## Find Similiar Movie

In [10]:
    movie_mat = movies_df[movies_df['movie_id'] == 4100].iloc[:,4:]
    np.array(movie_mat)


array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0]])

In [11]:
np.array(movies_df.iloc[:,4:]).transpose()

array([[1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [12]:
def find_similiar_movie(movie_id: int, movies_df: pd.DataFrame = movies_df):
    #get row of given movie_id feature
    movie_mat = np.array(movies_df[movies_df['movie_id'] == movie_id].iloc[:,4:])[0]
    print(movie_mat)
    #get feature matrix of all movies
    movies_mat = np.array(movies_df.iloc[:,4:])
    
    #calculate similiarity between given movie and all movie
    dot_prod = movie_mat.dot(movies_mat.transpose())

    #get the most likely movie
    movie_rows = np.where(dot_prod == np.max(dot_prod))[0]
    movie_row = np.random.choice(movie_rows)
    movie = movies_df.iloc[movie_row]['movie']
    return movie

In [13]:
find_similiar_movie(2649128, movies_df)

[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1]


'Thani Oruvan (2015)'

In [14]:
def funk_svd_fit(reviews_df: pd.DataFrame, latent_features=20, learning_rate=0.005, iters=10):
    user_review_df = reviews_df.groupby(['user_id', 'movie_id'])['rating'].max().unstack()
    user_review_mat = np.array(user_review_df)
    n_users = user_review_df.shape[0]
    n_movies = user_review_df.shape[1]
    n_ratings = np.count_nonzero(user_review_df)

    u_mat = np.random.rand(n_users, latent_features)
    v_mat = np.random.rand(latent_features, n_movies)

    print("Iterations | MSE")

    for iteration in range(iters):
        sse_cum = 0
        for i in range(n_users):
            for j in range(n_movies):
                if user_review_mat[i,j] > 0:
                    diff = user_review_mat[i,j] - u_mat[i,:].dot(v_mat[:,j])
                    sse_cum += diff**2

                    for k in range(latent_features):
                        u_mat[i,k] += learning_rate * 2 * diff * v_mat[k,j]
                        v_mat[k,j] += learning_rate * 2 * diff * u_mat[i,k]
    
        print("%d \t\t %f" % (iteration+1, sse_cum / n_ratings))
    
    return u_mat, v_mat



In [15]:
u_mat, v_mat = funk_svd_fit(reviews_df, iters=20)

Iterations | MSE
1 		 0.005841
2 		 0.003461
3 		 0.002466
4 		 0.001876
5 		 0.001483
6 		 0.001201
7 		 0.000990
8 		 0.000826
9 		 0.000696
10 		 0.000591
11 		 0.000504
12 		 0.000433
13 		 0.000373
14 		 0.000322
15 		 0.000279
16 		 0.000243
17 		 0.000212
18 		 0.000185
19 		 0.000162
20 		 0.000142


In [29]:
def predict(u_mat, v_mat, user, movie):
    return u_mat[user,:].dot(v_mat[:,movie])

predict(u_mat, v_mat, 1270, 50)

7.210229516362975

In [61]:
a = np.array([np.nan, np.nan])
a[0]

nan